#!/bin/sh
# Xcode Cloud runs this after cloning, before resolving packages and building.
# The Xcode project is generated by XcodeGen from project.yml, so regenerate it
# here to guarantee the build uses the committed configuration.
set -e

brew install xcodegen

cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate
